{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stubcall/0.1.0/stubcall-0.1.0.module",
    "group": "io.github.rasulmingazov",
    "module": "stubcall",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "stubcall-jvm-0.1.0.jar",
          "url": "stubcall-jvm-0.1.0.jar",
          "size": 23283,
          "sha512": "ceb3605bc7f6c9af7111910a1bcdf9f6cfaa56d1e9e75a48ed0cc156ff6a8172389103c956bcdbba243f979c98d929a5145011dd98be14352ec0fc31f39eddf9",
          "sha256": "00d1c0fa05ea568aca90ef07f6266ab7d6b6eccab6637d03ccd899f3dc2d95de",
          "sha1": "c6c10b0ba7f809f26282b4f726d496fc6c18c66d",
          "md5": "7a8febfea2dbf5c92b9a2d6699fd0660"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "stubcall-jvm-0.1.0.jar",
          "url": "stubcall-jvm-0.1.0.jar",
          "size": 23283,
          "sha512": "ceb3605bc7f6c9af7111910a1bcdf9f6cfaa56d1e9e75a48ed0cc156ff6a8172389103c956bcdbba243f979c98d929a5145011dd98be14352ec0fc31f39eddf9",
          "sha256": "00d1c0fa05ea568aca90ef07f6266ab7d6b6eccab6637d03ccd899f3dc2d95de",
          "sha1": "c6c10b0ba7f809f26282b4f726d496fc6c18c66d",
          "md5": "7a8febfea2dbf5c92b9a2d6699fd0660"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "stubcall-jvm-0.1.0-sources.jar",
          "url": "stubcall-jvm-0.1.0-sources.jar",
          "size": 5573,
          "sha512": "c908a0b4bef6b972d580a472584703ddc8f017f86aeb89b2e918821ed5831d6ce6255b0f067268b31433ea2dad19a01ffaeffbc70132125bd0a029ba4c62f572",
          "sha256": "b360b59060d483745a893daad95308a87ff951c1b9d68ba2147e511082fd43aa",
          "sha1": "1b550c6a5429c05a91498d0888129fa19001aa00",
          "md5": "88a5550725e80256cbca01581c6bedf1"
        }
      ]
    }
  ]
}
