package app.yap.core.design.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class YapColors(
    val accent: Color,
    val accentFill: Color,
    val action: Color,
    val background: Color,
    val bodyMuted: Color,
    val caption: Color,
    val card: Color,
    val cardTrack: Color,
    val chip: Color,
    val cta: Color,
    val doneName: Color,
    val error: Color,
    val faint: Color,
    val hairline: Color,
    val hairlineStrong: Color,
    val handle: Color,
    val highlight: Color,
    val link: Color,
    val muted: Color,
    val navBar: Color,
    val navBorder: Color,
    val navIdle: Color,
    val notice: Color,
    val onAccentFill: Color,
    val onAction: Color,
    val onBackground: Color,
    val onCard: Color,
    val onCta: Color,
    val onError: Color,
    val onHighlight: Color,
    val onNotice: Color,
    val onPill: Color,
    val onSurface: Color,
    val outline: Color,
    val pill: Color,
    val pipDone: Color,
    val pressed: Color,
    val scrim: Color,
    val sectionLabel: Color,
    val sheet: Color,
    val surface: Color,
    val track: Color,
)

internal val LightYapColors = YapColors(
    accent = Color(0xFF0B0A0D),
    accentFill = Color(0xFFD9FF57),
    action = Color(0xFF0B0A0D),
    background = Color(0xFFFFFFFF),
    bodyMuted = Color(0xFF5F5A6B),
    caption = Color(0xFF77717F),
    card = Color(0xFF0B0A0D),
    cardTrack = Color(0xFFFFFFFF).copy(alpha = 0.18f),
    chip = Color(0xFFF5F5F4),
    cta = Color(0xFF0B0A0D),
    doneName = Color(0xFF77717F),
    error = Color(0xFFFDECEC),
    faint = Color(0xFF77717F),
    hairline = Color(0xFF0B0A0D).copy(alpha = 0.10f),
    hairlineStrong = Color(0xFF0B0A0D).copy(alpha = 0.22f),
    handle = Color(0xFF0B0A0D).copy(alpha = 0.20f),
    highlight = Color(0xFFD9FF57),
    link = Color(0xFF0B0A0D),
    muted = Color(0xFF5F5A6B),
    navBar = Color(0xFF0B0A0D),
    navBorder = Color(0xFF0B0A0D).copy(alpha = 0.90f),
    navIdle = Color(0xFF8F8899),
    notice = Color(0xFFD9FF57),
    onAccentFill = Color(0xFF0B0A0D),
    onAction = Color(0xFFD9FF57),
    onBackground = Color(0xFF0B0A0D),
    onCard = Color(0xFFFAF9F6),
    onCta = Color(0xFFD9FF57),
    onError = Color(0xFFB42323),
    onHighlight = Color(0xFF0B0A0D),
    onNotice = Color(0xFF0B0A0D),
    onPill = Color(0xFF0B0A0D),
    onSurface = Color(0xFF0B0A0D),
    outline = Color(0xFF0B0A0D).copy(alpha = 0.10f),
    pill = Color(0xFFD9FF57),
    pipDone = Color(0xFF0B0A0D),
    pressed = Color(0xFF5F5A6B),
    scrim = Color(0xFF0B0A0D).copy(alpha = 0.35f),
    sectionLabel = Color(0xFF77717F),
    sheet = Color(0xFFFFFFFF),
    surface = Color(0xFFFFFFFF),
    track = Color(0xFF0B0A0D).copy(alpha = 0.10f),
)

internal val DarkYapColors = YapColors(
    accent = Color(0xFFD9FF57),
    accentFill = Color(0xFFD9FF57),
    action = Color(0xFFD9FF57),
    background = Color(0xFF08070A),
    bodyMuted = Color(0xFF8F8899),
    caption = Color(0xFF5B5765),
    card = Color(0xFF1A1920),
    cardTrack = Color(0xFFE2E2E2).copy(alpha = 0.15f),
    chip = Color(0xFFE2E2E2).copy(alpha = 0.07f),
    cta = Color(0xFFD9FF57),
    doneName = Color(0xFF8F8899),
    error = Color(0xFFFF6B6B).copy(alpha = 0.14f),
    faint = Color(0xFF6B6675),
    hairline = Color(0xFFE2E2E2).copy(alpha = 0.12f),
    hairlineStrong = Color(0xFFE2E2E2).copy(alpha = 0.28f),
    handle = Color(0xFFE2E2E2).copy(alpha = 0.25f),
    highlight = Color(0xFFD9FF57),
    link = Color(0xFFFAF9F6),
    muted = Color(0xFF8F8899),
    navBar = Color(0xFF1C1A22).copy(alpha = 0.82f),
    navBorder = Color(0xFFE2E2E2).copy(alpha = 0.12f),
    navIdle = Color(0xFF8F8899),
    notice = Color(0xFFD9FF57),
    onAccentFill = Color(0xFF0B0A0D),
    onAction = Color(0xFF0B0A0D),
    onBackground = Color(0xFFFAF9F6),
    onCard = Color(0xFFFAF9F6),
    onCta = Color(0xFF0B0A0D),
    onError = Color(0xFFFF8F8F),
    onHighlight = Color(0xFF0B0A0D),
    onNotice = Color(0xFF0B0A0D),
    onPill = Color(0xFFD9FF57),
    onSurface = Color(0xFFFAF9F6),
    outline = Color(0xFFE2E2E2).copy(alpha = 0.14f),
    pill = Color(0xFFD9FF57).copy(alpha = 0.14f),
    pipDone = Color(0xFFD9FF57),
    pressed = Color(0xFFD9FF57),
    scrim = Color(0xFF050406).copy(alpha = 0.55f),
    sectionLabel = Color(0xFF7C7787),
    sheet = Color(0xFF16151A),
    surface = Color(0xFF15141A),
    track = Color(0xFFE2E2E2).copy(alpha = 0.13f),
)
